### PR TITLE
Multiple messages per session fix

### LINKED ISSUE #4: Only latest flash message is shown
# Issue / Motivation:
I'd like to have multiple flash messages shown at once, only the latest is shown in views

## Expected behavior:

```
flash()->success('You successfully read this important alert message.')
       ->info('This alert needs your attention, but it\'s not super important.')
       ->warning('Better check yourself, you\'re not looking too good.')
       ->error('Change a few things up and try submitting again.')
       ->overlay('One fine body...');

       dd($request);
```

The session should contain multiple flash messages. 

## Actual behavior:
Only the latest flash message "One fien boby" is indeed there

Can you help me ?

### PR DESCRIPTION
**Pull request by philippejadin**
Fixes #4 

This is a trick found here : http://stackoverflow.com/a/23316557

### CODE REVIEW

**Comment by DraperStudio** [comment]
Could you remove the `commit` method too since it isn't required anymore?

**Comment by DraperStudio** [comment]
Did you test with a Laravel installation if this properly shows the messages? Will merge if you confirm this.

**Comment by philippejadin** [comment]
I confirm it works on an existing Laravel project where it will be of great use !

( the project is here btw : https://github.com/philippejadin/Mobilizator )

**Comment by DraperStudio** [comment]
Thanks, you can now pull in `^0.2.0`.

**Pull request merged**
